### ISSUE TITLE
Help regarding model creation code 

### ISSUE THREAD

**Issue by Aayush204** [Tech-Cravers/Gesture-Speech#8]
please share the link for the file or python code used to create the trained model

**Comment by Aryan4786** [comment]
Let me check

**Comment by Aayush204** [comment]
okay bro i am waiting and we are thinking to run this project with a dataset available on kaggle thats the reason i am asking

**Comment by RushilVerma** [comment]
please refer to the code structure :
dataProcessing_pics.py ->to extract data from pics of folder structure
dataset
|-A
|-B
|- :
|-Z
please configure directory to local address line 38
after processing it is saved as pickle file used by
tranningCNN.py ->to convert that to model
testing_model.py->testing 
gesture to speech.py -> to use as final product

**Comment by Aayush204** [comment]
so that means i want to use indian sign language dataset from kaggle i need to do these steps and if the parameters are same as your trained model will the dataset work ?

**Comment by RushilVerma** [comment]
Yes
 Data set after processing if you dont want to store in pickle file could directly be fed to training model (in code trainning CNN.py)in form of variable x and y (line 85 dataProcessing_pics.py)

**Comment by Aayush204** [comment]
okay bro will ask for any further help if needed

**Comment by Aayush204** [comment]
what to put in the { bracket folder ? just blank images or an empty folder name { will work ?

**Comment by Aayush204** [comment]
Please give Your dataset folder or link

**Comment by Aayush204** [comment]
how many letters from 26 
your model was able to recognize ?

**Comment by RushilVerma** [comment]
Hi ayush dataset could not be shared at the moment but can be created by by data processing files please refer the they are fully commented for eny functional description
All 26 letters with additional blank space represented by { is recognized by model

**Comment by RushilVerma** [comment]
stale thread
